_wandb:
    value:
        cli_version: 0.26.1
        e:
            q1dbluwqrdnbbw5y9cnqyhvrmvnr1429:
                args:
                    - --optimize
                    - "0"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "207818493952"
                        used: "122376187904"
                email: starke@b-tu.de
                executable: /home/rolf/anaconda3/envs/cvmgr/bin/python
                git:
                    commit: c4d7591428478acc7c07d5f18c066eb9e069e767
                    remote: https://github.com/rolfstarke/cvmgr.git
                gpu: NVIDIA RTX A4000
                gpu_count: 5
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-a953b6be-4f1c-6e17-37f2-314c5185e2df
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-9323c0ec-5d7e-2d7d-352d-772492fa96e9
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-2aae169b-ecb8-ac84-90ad-19ccffecae32
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-4f5c9e64-ae39-b646-328c-29f65686286f
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-7de1de81-6635-42a0-ab53-92f20494e79b
                host: lnx-1.bauwesen.local
                memory:
                    total: "475512504320"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.39
                program: /home/rolf/GIT/cvmgr/main.py
                python: CPython 3.10.20
                root: /home/rolf/GIT/cvmgr
                startedAt: "2026-05-25T13:11:52.944866Z"
                writerId: q1dbluwqrdnbbw5y9cnqyhvrmvnr1429
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 30
                - 35
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 30
                - 35
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.10.20
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
bgr:
    value: 0.34469488696294237
box:
    value: 11.299685363580851
close_mosaic:
    value: 2
cls:
    value: 0.3442633816343592
cls_pw:
    value: 0.7532201321513863
copy_paste:
    value: 0.4042377262557343
cutmix:
    value: 0.8713759872347111
dataset_name:
    value: airvent
degrees:
    value: 22.91451197515569
dfl:
    value: 1.389788558336195
fliplr:
    value: 0.9027597742868495
flipud:
    value: 0.8032404681500654
hsv_h:
    value: 0.08136391776581739
hsv_s:
    value: 0.6779937789121822
hsv_v:
    value: 0.5735855376801788
lr0:
    value: 0.0009200803189416678
lrf:
    value: 0.8215879525465551
mixup:
    value: 0.6115159310064916
momentum:
    value: 0.7865637814475879
mosaic:
    value: 0.6134664511070148
perspective:
    value: 7.231710606764641e-05
scale:
    value: 0.7735479770703002
shear:
    value: 0.4589759558727857
translate:
    value: 0.4231383076408397
warmup_epochs:
    value: 3.2748639958070163
warmup_momentum:
    value: 0.7405494778904674
weight_decay:
    value: 0.0007806363759257764
