agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.2581621691110719
box: 5.902420820555827
cache: false
cfg: null
classes: null
close_mosaic: 9
cls: 2.9868776350806674
cls_pw: 0.5069539732331398
compile: false
conf: null
copy_paste: 0.4117683702279864
copy_paste_mode: flip
cos_lr: false
cutmix: 0.6923558093060274
data: null
degrees: 26.646095246436573
deterministic: true
device: null
dfl: 10.216174617510113
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 3
erasing: 0.4
exist_ok: false
fliplr: 0.45749571935788624
flipud: 0.2017821115803476
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.03681698093345219
hsv_s: 0.8975696935750356
hsv_v: 0.36387379597963254
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.0030682050572509215
lrf: 0.1663992214663533
mask_ratio: 4
max_det: 300
mixup: 0.5776022201729856
mode: train
model: yolo26n-seg.pt
momentum: 0.8211439977344805
mosaic: 0.4283610546985705
multi_scale: 0.0
name: mirror
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: null
perspective: 8.970527830909485e-05
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.6548609020214557
seed: 0
shear: 5.419884750549723
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.08604974115396555
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 2.1717111486745666
warmup_momentum: 0.7316550324491844
weight_decay: 4.562278274932615e-05
workers: 8
workspace: null
