_wandb:
    value:
        cli_version: 0.26.1
        e:
            kn85fosulmdk4l9g5xs8fh2p7iprw7oc:
                args:
                    - --optimize
                    - --dataset
                    - deskchair
                    - --gpu
                    - "4"
                    - --iterations
                    - "120"
                codePath: main.py
                codePathLocal: main.py
                email: starke@b-tu.de
                executable: /home/rolf/anaconda3/envs/cvmgr/bin/python
                git:
                    commit: c4d7591428478acc7c07d5f18c066eb9e069e767
                    remote: https://github.com/rolfstarke/cvmgr.git
                host: lnx-1.bauwesen.local
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.39
                program: /home/rolf/GIT/cvmgr/main.py
                python: CPython 3.10.20
                root: /home/rolf/GIT/cvmgr
                startedAt: "2026-06-17T15:52:48.123584Z"
                writerId: kn85fosulmdk4l9g5xs8fh2p7iprw7oc
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 30
                - 35
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 30
                - 35
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 15
            "4": 3.10.20
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
