name: cvmgr
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - jupyter
  - pip:
      - roboflow
      - ultralytics
      - fiftyone
      - ipywidgets
      - opencv-python
      - supervision
      - git+https://github.com/huggingface/transformers.git#egg=transformers
      - torch
      - torchvision
      - huggingface-hub

#variables:
#  LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: true
#  LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /mnt/EBI-SHARE/06_Data/labelstudio