name: cvmgr
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - jupyter
  - pip:
      - roboflow
      - ultralytics
      - fiftyone
      - ipywidgets
      - opencv-python
      - supervision
      - git+https://github.com/huggingface/transformers.git#egg=transformers
      - torch
      - torchvision
      - huggingface-hub
      - umap-learn
      - wandb
      - sam2
      - "ray[tune]"
      - optuna
      - hyperopt

variables:
  LD_LIBRARY_PATH: /home/rolf/anaconda3/envs/cvmgr/lib/python3.10/site-packages/nvidia/cu13/lib