# those must match the name in datasets.yaml

datasets_to_download:
# - boiler
# - carpet
# - ceilinglight
# - desk
# - deskchair
# - door
# - elevator
# - exitlight
# - faucet
# - filing_cabinet
# - glass
# - radiator
# - mirror
# - sink
# - toilet
# - airvent

# - windowframe
# - oi_v7_custom_54
# - oi_v7_custom_13
# - oi_v7_custom_null
# - oi_v7_custom_negative
# - powersocket_sam3
# - mock_data_1
# - mock_data_2
# - mark_lane_leuthener_21_FULLHD
# - mark_lane_leuthener_21_HD
# - mark_lane_leuthener_21_ORIGINAL
#  - window


datasets_to_train:
# - boiler
# - carpet
# - ceilinglight
# - desk
 - deskchair
 - door
 - elevator
 - exitlight
 - faucet
 - filing_cabinet
# - glass
 - radiator
 - mirror
 - sink
# - toilet
# - airvent

text_prompt_datasets:
#  - oi_v7_custom_negative
  - mark_lane_leuthener_21_ORIGINAL

# - powersocket_test

visual_prompt_datasets:
  - mark_lane_leuthener_21_ORIGINAL

analyse_datasets:
  - mark_lane_leuthener_21_ORIGINAL


models_to_optimize:
#  - airvent
# - boiler
# - ceilinglight
# - deskchair
# - door
#  - elevator
 - exitlight


# - windowframe
# - airvent
# - duct
# - heater
# - toilet

models_to_evaluate:
  - train-29

datasets_to_correct:
  - mark_lane_leuthener_21_ORIGINAL

datasets_to_pull:
