agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.30504725830162693
box: 5.495987368935235
cache: false
cfg: null
classes: null
close_mosaic: 25
cls: 1.8193276747246412
cls_pw: 0.0008197917600628185
compile: false
conf: null
copy_paste: 0.04898849927425374
copy_paste_mode: flip
cos_lr: true
cutmix: 0.18506558866835615
data: null
degrees: 14.649467553654263
deterministic: true
device: null
dfl: 2.0
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 400
erasing: 0.4
exist_ok: false
fliplr: 0.5
flipud: 0.0
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.0047880777865505
hsv_s: 0.5
hsv_v: 0.6
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.003060057155194744
lrf: 0.3706762375486293
mask_ratio: 4
max_det: 300
mixup: 0.9203223250805856
mode: train
model: yolo26n-seg.pt
momentum: 0.796938868299304
mosaic: 0.45046567203339816
multi_scale: 0.5
name: ceilinglight
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: 50
perspective: 0.0007678895403389158
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.9
seed: 0
shear: 2.7838170451968383
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: segment
time: 12
tracker: botsort.yaml
translate: 0.4251935539628928
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 2.709404607762248
warmup_momentum: 0.15394050364804554
weight_decay: 0.0007015204398451057
workers: 8
workspace: null
