agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.08147747422792212
box: 15.363940892792812
cache: false
cfg: null
classes: null
close_mosaic: 15
cls: 1.7220983588620564
cls_pw: 0.35161028794500004
compile: false
conf: null
copy_paste: 0.12789404453424597
copy_paste_mode: flip
cos_lr: true
cutmix: 0.44874741607207547
data: null
degrees: 13.867028910428541
deterministic: true
device: null
dfl: 2.0
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 150
erasing: 0.4
exist_ok: false
fliplr: 0.275650385918493
flipud: 0.0809139164040184
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.005823995177699492
hsv_s: 0.7725308949812644
hsv_v: 0.651231045134849
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.00617904035522068
lrf: 0.4581969321398364
mask_ratio: 4
max_det: 300
mixup: 0.2188098957778783
mode: train
model: yolo26n-seg.pt
momentum: 0.937
mosaic: 0.5701041504814445
multi_scale: 0.5
name: desk
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: 50
perspective: 0.0003274790769098643
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.7
seed: 0
shear: 2.1244075311930657
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: segment
time: null
tracker: botsort.yaml
translate: 0.4720361733019446
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 1.139300605771298
warmup_momentum: 0.828287456128298
weight_decay: 0.0002960235467103261
workers: 8
workspace: null
