agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.07925472610242974
box: 19.79339042664724
cache: false
cfg: null
classes: null
close_mosaic: 15
cls: 1.8457641443870647
cls_pw: 0.2329733899313397
compile: false
conf: null
copy_paste: 0.1318213373835247
copy_paste_mode: flip
cos_lr: true
cutmix: 0.9566929432605025
data: null
degrees: 9.806187335367126
deterministic: true
device: null
dfl: 2.0
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 150
erasing: 0.4
exist_ok: false
fliplr: 0.3
flipud: 0.0
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.08430684270396177
hsv_s: 0.5
hsv_v: 0.6245651277628995
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.0029822451667545014
lrf: 0.8833173215481444
mask_ratio: 4
max_det: 300
mixup: 0.5941603735301877
mode: train
model: yolo26n-seg.pt
momentum: 0.800312999452177
mosaic: 0.45064949380074765
multi_scale: 0.5
name: exitlight
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: 50
perspective: 0.00032268692583013557
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.8
seed: 0
shear: 9.593830042395775
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: segment
time: null
tracker: botsort.yaml
translate: 0.0936917669562521
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 2.694735707046591
warmup_momentum: 0.9042986634258633
weight_decay: 0.0003309723136211551
workers: 8
workspace: null
