agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.2172100897860967
box: 16.11906637113652
cache: false
cfg: null
classes: null
close_mosaic: 25
cls: 1.2022563808315678
cls_pw: 0.21767151538365115
compile: false
conf: null
copy_paste: 0.5095067476335579
copy_paste_mode: flip
cos_lr: true
cutmix: 0.2515674142185432
data: null
degrees: 20.98644433479203
deterministic: true
device: null
dfl: 2.0
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 300
erasing: 0.4
exist_ok: false
fliplr: 0.1842889665455001
flipud: 0.1267000569293316
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.060025977248016525
hsv_s: 0.39274871709527365
hsv_v: 0.1873824514625586
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.00402068272547307
lrf: 0.01135188247944286
mask_ratio: 4
max_det: 300
mixup: 0.283692571445826
mode: train
model: yolo26n-seg.pt
momentum: 0.7296148298355347
mosaic: 0.9
multi_scale: 0.5
name: filing_cabinet
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: 50
perspective: 0.0007850168282666785
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.9
seed: 0
shear: 0.24920702849391968
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: segment
time: null
tracker: botsort.yaml
translate: 0.17462601368590233
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 2.5688159835123523
warmup_momentum: 0.46320063801132516
weight_decay: 0.00048817907149752935
workers: 8
workspace: null
