agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.39161116132651796
box: 13.628196893884862
cache: false
cfg: null
classes: null
close_mosaic: 25
cls: 0.7336892150013581
cls_pw: 0.8170445917431213
compile: false
conf: null
copy_paste: 0.47421548862892043
copy_paste_mode: flip
cos_lr: true
cutmix: 0.6020884306081997
data: null
degrees: 10.213774271824658
deterministic: true
device: null
dfl: 2.0
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 300
erasing: 0.4
exist_ok: false
fliplr: 0.6135357488251595
flipud: 0.07402489427586706
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.046345013724755725
hsv_s: 0.5629518136994551
hsv_v: 0.6227061245789806
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.007457216197090434
lrf: 0.21119004736568847
mask_ratio: 4
max_det: 300
mixup: 0.13647547297725474
mode: train
model: yolo26n-seg.pt
momentum: 0.9549703565571859
mosaic: 0.9740165667861694
multi_scale: 0.5
name: radiator
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: 50
perspective: 0.0003913585247418053
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.9
seed: 0
shear: 0.6381074426958426
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: segment
time: null
tracker: botsort.yaml
translate: 0.3
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 1.755756913581016
warmup_momentum: 0.10565490403174246
weight_decay: 0.0007844083359359635
workers: 8
workspace: null
