# the dataset names must match fiftyone
# structure for multipart datasets must match this formatting:
# dataset_name:
#   multipart: true
#   part1:
#     ...
#   part2:
#     ...

exitlight:
  host: roboflow
  format: yolov12
  type: "polylines"
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "exit_lights_relabeled"
  workspace: "made-srcnb"
  version: 1
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]  
  export_classes: [
    "Emergency exit sign"
  ]

exitlight_old:
  host: roboflow
  format: yolov12
  type: "detections"
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "exit-lights-s6bot"
  workspace: "made-srcnb"
  version: 5
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]  
  export_classes: [
    "Emergency exit sign"
  ]

ceilinglight:
  host: roboflow
  type: "detections"
  format: yolov12
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "light_detect_3"
  workspace: "tree-detection-zocbs"
  version: 3
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]     
  export_classes: [
    "Ceiling light"
  ]          

duct:
  host: roboflow
  type: "polylines"
  format: yolov12
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "ecw_14_detection-2-7jehm"
  workspace: "made-srcnb"
  version: 2
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]    
  export_classes: [
    "Duct"
  ] 

elevator:
  host: roboflow
  format: yolov12
  type: "polylines"
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "elevator-status-o09nl"
  workspace: "made-srcnb"
  version: 3
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]
  export_classes: [
    "Elevator",
  ]

airvent:
  host: roboflow
  type: "polylines"  
  format: yolov12
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "air-vent-hole-v2-jyymj"
  workspace: "made-srcnb"
  version: 2
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]
  export_classes: [
    "Vent"
  ]

windowframe:
  host: roboflow
  type: "polylines"
  format: yolov12
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "windowframe-ekvou"
  workspace: "made-srcnb"
  version: 2
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]
  export_classes: [
    "Window frame",
  ]

boiler:
  host: roboflow
  format: yolov12
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  project: "boiler-syvqj"
  workspace: "made-srcnb"
  version: 2
  type: "polylines"
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]
  export_classes: [
    "Boiler"
  ]

mark_lane_leuthener_custom_21_lowres:
  samples_per_split: 3
  type: "detections"
  host: roboflow
  format: yolov5
  # formats include: clip, coco, coco-mmdetection, createml, darknet, multiclass, tensorflow, tfrecord, voc, yolokeras, yolov4pytorch, yolov4scaled, yolov5-obb, yolov5pytorch, yolov7pytorch, yolov8, yolov8-obb, yolov9, yolov11, yolov12, mt-yolov6, retinanet, benchmarker, paligemma, paligemma-txt, florence2-od, openai
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  workspace: "made-srcnb"
  project: "isarc2"
  version: 4
  download_splits: ["train", "valid", "test"]
  export_splits: ["train", "valid", "test"]

mark_lane_leuthener_custom_21:
  #samples_per_split:
  type: "detections"
  host: roboflow
  format: yolov5
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  workspace: "made-srcnb"
  project: "isarc2"
  version: 5
  download_splits: ["train", "valid", "test"]
  classes: [
    "Desk chair",
    "Conference chair",
    "Desk",
    "Filing cabinet",
    "Heater",
    "Boiler",
    "Air flow grill",
    "Elevator",
    "Ductwork",
    "Ceiling light",
    "Wall lights",
    "Emergency exit sign",
    "Mirror",
    "Toilet",
    "Sink",
    "Faucet",
    "Raised access flooring",
    "Door",
    "Window frame",
    "Glas internal",
    "Glas external"
  ]

mark_lane_leuthener_custom_21_fullhd:
  #samples_per_split:
  type: "detections"
  host: roboflow
  format: yolov5
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  workspace: "made-srcnb"
  project: "isarc2"
  version: 6
  download_splits: ["train", "valid", "test"]
  classes: [
    "Desk chair",
    "Conference chair",
    "Desk",
    "Filing cabinet",
    "Heater",
    "Boiler",
    "Air flow grill",
    "Elevator",
    "Ductwork",
    "Ceiling light",
    "Wall lights",
    "Emergency exit sign",
    "Mirror",
    "Toilet",
    "Sink",
    "Faucet",
    "Raised access flooring",
    "Door",
    "Window frame",
    "Glas internal",
    "Glas external"
  ]


mark_lane_leuthener_custom_21_hd:
  #samples_per_split: 2
  type: "detections"
  host: roboflow
  format: yolov5
  api_key: "AgfWlgODe2lXi5Nh5VTu"
  workspace: "made-srcnb"
  project: "isarc2"
  version: 8
  download_splits: ["train", "valid", "test"]
  classes: [
    "Desk chair",
    "Conference chair",
    "Desk",
    "Filing cabinet",
    "Heater",
    "Boiler",
    "Air flow grill",
    "Elevator",
    "Ductwork",
    "Ceiling light",
    "Wall lights",
    "Emergency exit sign",
    "Mirror",
    "Toilet",
    "Sink",
    "Faucet",
    "Raised access flooring",
    "Door",
    "Window frame",
    "Glas internal",
    "Glas external"
  ]

oi_v7_complete:
  #samples_per_split: null  # or remove line entirely 
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: "detections"
  download_splits: ["train", "validation", "test"]
  #download_classes: null   # Download all classes instead of empty list
  export_splits: ["train", "val", "test"]   
  export_classes: ["chair"]

oi_v7_custom_clean:
  samples_per_split: 100000
  host: fiftyone_zoo
  origin: open-images-v7
  type: "polylines"
  download_splits: ["train", "validation", "test"]
  download_classes: []   
  export_splits: ["train", "val", "test"]   
  export_classes: ["white heating radiator", 
         "window", 
         "door",
         "socket", 
         "white kitchen appliance",
         "toilet bowl", 
         "water heater", 
         "bath tub", 
         "sink", 
         "smoke detector",
         "windowsill"]
  conf_tresholds: 
    "white heating radiator": 0.3
    "window": 0.3
    "door": 0.3
    "socket": 0.3
    "white kitchen appliance": 0.3
    "toilet bowl": 0.3
    "water heater": 0.3
    "bath tub": 0.3
    "sink": 0.3
    "smoke detector": 0.3
    "windowsill": 0.3
  

oi_v7_custom_clean_10:
  samples_per_split: 10
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: "detections"
  download_splits: ["train", "validation", "test"]
  download_classes: []   
  export_splits: ["train", "val", "test"]   
  export_classes: ["chair"]


oi_v7_custom_null:
  samples_per_split: 100
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: "detections"
  download_splits: ["train", "validation", "test"]
  download_classes:    
  export_splits: ["train", "val", "test"]   
  export_classes: 

oi_v7_custom_13:
  multipart: true
  oi_v7_custom_8:
    samples_per_split: 100
    host: fiftyone_zoo
    origin: open-images-v7
    download_type: "detections"    
    download_splits: ["train", "validation", "test"]  
    download_classes:            
      - "Door"
      - "Window"
      - "Bathtub"
      - "Sink"
      - "Lamp"
      - "Mechanical fan"
      - "Chair"
      - "Desk"
  oi_v7_custom_5:
    samples_per_split: 100
    host: fiftyone_zoo
    origin: open-images-v7
    download_type: "segmentations"    
    download_splits: ["train", "validation", "test"]  
    download_classes:            
      - "Filing Cabinet"
      - "Heater"
      - "Power plugs and sockets"
      - "Light switch"
      - "Toilet"

      
oi_v7_custom_3:
  multipart: true
  mock_data_1:
    samples_per_split: 10
    host: fiftyone_zoo
    origin: open-images-v7
    download_type: &type1 "detections"    
    download_splits: ["train", "validation", "test"]  
    download_classes: &classes1            
      - "Door"
    export_splits: ["train", "val", "test"]                 
    export_classes: *classes1              
    export_type: "segmentations"
  mock_data_2:
    samples_per_split: 10
    host: fiftyone_zoo
    origin: open-images-v7
    download_type: &type2 "segmentations"
    download_splits: ["train", "validation", "test"]
    download_classes: &classes2
      - "Door handle"
    export_splits: ["train", "val", "test"]   
    export_classes: *classes2
    export_type: "segmentations"


oi_v7_custom_54:
  samples_per_split: 100
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: "detections"
  download_splits: ["train", "validation", "test"]
  download_classes: &classes4
    - "Cabinetry"
    - "Bidet"
    - "Desk"
    - "Oven"
    - "Couch"
    - "Whiteboard"
    - "Door"
    - "Shower"
    - "Vase"
    - "Wardrobe"
    - "Gas stove"
    - "Nightstand"
    - "Window blind"
    - "Street light"
    - "Power plugs and sockets"
    - "Door handle"
    - "Bathtub"
    - "Houseplant"
    - "Kitchen utensil"
    - "Light switch"
    - "Ceiling fan"
    - "Sofa bed"
    - "Heater"
    - "Curtain"
    - "Bed"
    - "Fireplace"
    - "Kitchenware"
    - "Bookcase"
    - "Refrigerator"
    - "Filing cabinet"
    - "Table"
    - "Bathroom cabinet"
    - "Mirror"
    - "Chest of drawers"
    - "Infant bed"
    - "Cupboard"
    - "Picture frame"
    - "Coffee table"
    - "Toilet"
    - "Countertop"
    - "Waste container"
    - "Furniture"
    - "Bench"
    - "Window"
    - "Closet"
    - "Lamp"
    - "Flowerpot"
    - "Drawer"
    - "Microwave oven"
    - "Shelf"
    - "Light bulb"
    - "Kitchen & dining room table"
    - "Bathroom accessory"
    - "Kitchen appliance"
  export_splits: ["train", "val", "test"]   
  export_classes: *classes4
  export_type: 

oi_v7_custom_1:
  samples_per_split: 30
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: "segmentations"    
  download_splits: ["train", "validation", "test"]  
  download_classes:            

  export_splits: ["train", "val", "test"]   
  export_classes:            

  export_type: "segmentations"