# the dataset names must match fiftyone
# the splits 

mock_data_1:
  samples_per_split: 100
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: &type1 "detections"    
  download_splits: ["train", "validation", "test"]  
  download_classes: &classes1            
    - "Door"
  export_splits: ["train", "val", "test"]                 
  export_classes: *classes1              
  export_type: *type1   
    

mock_data_2:
  samples_per_split: 100
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: &type2 "detections"
  download_splits: ["train", "validation", "test"]
  download_classes: &classes2
    - "Door handle"
  export_splits: ["train", "val", "test"]   
  export_classes: *classes2
  export_type: *type2

oi_v7_custom_54:
  samples_per_split: 100
  host: fiftyone_zoo
  origin: open-images-v7
  download_type: &type3 "detections"
  download_splits: ["train", "validation", "test"]
  download_classes: &classes3
    - "Cabinetry"
    - "Bidet"
    - "Desk"
    - "Oven"
    - "Couch"
    - "Whiteboard"
    - "Door"
    - "Shower"
    - "Vase"
    - "Wardrobe"
    - "Gas stove"
    - "Nightstand"
    - "Window blind"
    - "Street light"
    - "Power plugs and sockets"
    - "Door handle"
    - "Bathtub"
    - "Houseplant"
    - "Kitchen utensil"
    - "Light switch"
    - "Ceiling fan"
    - "Sofa bed"
    - "Heater"
    - "Curtain"
    - "Bed"
    - "Fireplace"
    - "Kitchenware"
    - "Bookcase"
    - "Refrigerator"
    - "Filing cabinet"
    - "Table"
    - "Bathroom cabinet"
    - "Mirror"
    - "Chest of drawers"
    - "Infant bed"
    - "Cupboard"
    - "Picture frame"
    - "Coffee table"
    - "Toilet"
    - "Countertop"
    - "Waste container"
    - "Furniture"
    - "Bench"
    - "Window"
    - "Closet"
    - "Lamp"
    - "Flowerpot"
    - "Drawer"
    - "Microwave oven"
    - "Shelf"
    - "Light bulb"
    - "Kitchen & dining room table"
    - "Bathroom accessory"
    - "Kitchen appliance"
  export_splits: ["train", "val", "test"]   
  export_classes: *classes3
  export_type: *type3