optimize:
  model: yolo26n-seg.pt
  epochs: 120
  batch: 32
  workers: 0
  gpu_per_trial: 1
  iterations: 60
  search_alg: "optuna"
  cache: "ram"

train:
  workers: 4
  batch: -1
  cache: "ram"
  epochs: 3000
  patience: 100
  model: yolo26x-seg.pt

sam:
  sam3_query_batch_size: 1
  sam3_empty_cache_every: 1
  sam3_confidence_threshold: 0.1
  sam3_visual_conf_threshold: 0.1
