optimize:
  cuda_visible_devices: "1"
  model: yolo26n-seg.pt
  epochs: 80
  batch: -1
  workers: 8
  gpu_per_trial: 1
  iterations: 150
  search_alg: "optuna"


train:
  cuda_visible_devices: "1"
  workers: 8
  batch: -1

sam:
  cuda_visible_devices: "0"