


DATASET_LOCATIONS:
#  - /mnt/EBI-SHARE/06_Data/labelstudio/datasets/multiclass/ebi-fused-4/data.yaml
#  - /mnt/EBI-SHARE/06_Data/labelstudio/datasets/beer/bier_ki-1-yolov8/data.yaml
#  - /mnt/EBI-SHARE/06_Data/labelstudio/datasets/rabbits/kaninchen-2-yolov8/data.yaml
#  - /mnt/EBI-SHARE/06_Data/labelstudio/datasets/test/dataset.yaml
- /mnt/EBI-SHARE/06_Data/labelstudio/datasets/multiclass/ebi-rundgang-fused-qooqx-1-yolov8/data.yaml

TRAINING_CONFIGURATIONS:
  - # epochs: 10
    img_size: 640
    time: 2 # Time in hours 
    patience: 100 # number of epochs with no improvement before stopping
    batch: -1 # Use the default "chunks" to split the dataset for computation, -1 is auto 60% GPU utilization
#    epochs: 1
  #   img_size: 640
  #   time: 3 # Time in hours 
  #   patience: 15 # number of epochs with no improvement before stopping
  #   batch: -1 # Use the default "chunks" to split the dataset for computation, -1 is auto 60% GPU utilization
  

MODEL: 
EVALUATION_DATASET: 

#ebi full model

#DATASET_TYPE: multiclass
#DATASET_TYPE: beer
#DATASET_TYPE: rabbits
DATASET_TYPE: multiclass
MODEL_PARENT_DIR: /mnt/EBI-SHARE/06_Data/labelstudio/models


models:
  doors:
    Door: 0.6
  windows:
    window: 0.6
  lights:
    light: 0.6
  open-images-v7:
    classes:





roboflow_datasets:
  ebi_full:
    api_key: "AgfWlgODe2lXi5Nh5VTu"
    workspace: "made-srcnb"
    project: "ebi-fused"
    version: 4
    type: "multiclass"

  ebi_rundgang:
    api_key: "ADColuoy8Ft64vwHwB5u"
    workspace: "rundgang"
    project: "ebi-rundgang-fused-qooqx"
    version: 1
    type: "multiclass"

  rabbits:
    api_key: "AgfWlgODe2lXi5Nh5VTu"
    workspace: "tafeln"
    project: "kaninchen"
    version: 2
    type: "rabbits"

  beer:
    api_key: "AgfWlgODe2lXi5Nh5VTu"
    workspace: "tree-detection-zocbs"
    project: "bier_ki"
    version: 1
    type: "beer"

  windows:
    api_key: "AgfWlgODe2lXi5Nh5VTu"
    workspace: "tafeln"
    project: "fensterfurmodel"
    version: 5
    type: "windows"

  lights:
    api_key: "AgfWlgODe2lXi5Nh5VTu"
    workspace: "tree-detection-zocbs"
    project: "light_detect_3"
    version: 2
    type: "lights"

  ebi_evaluation:
    api_key: "AgfWlgODe2lXi5Nh5VTu"
    workspace: "made-srcnb"
    project: "room312_and_leuthener"
    version: 2
    type: "multiclass"

fiftyone_zoo:
  open-images-v7:
    classes:
    - "Cabinetry"
    - "Bidet"
    - "Desk"
    - "Oven"
    - "Couch"
    - "Whiteboard"
    - "Door"
    - "Shower"
    - "Vase"
    - "Wardrobe"
    - "Gas stove"
    - "Nightstand"
    - "Window blind"
    - "Street light"
    - "Power plugs and sockets"
    - "Door handle"
    - "Bathtub"
    - "Houseplant"
    - "Kitchen utensil"
    - "Light switch"
    - "Ceiling fan"
    - "Sofa bed"
    - "Heater"
    - "Curtain"
    - "Bed"
    - "Fireplace"
    - "Kitchenware"
    - "Bookcase"
    - "Refrigerator"
    - "Filing cabinet"
    - "Table"
    - "Bathroom cabinet"
    - "Mirror"
    - "Chest of drawers"
    - "Infant bed"
    - "Cupboard"
    - "Picture frame"
    - "Coffee table"
    - "Toilet"
    - "Countertop"
    - "Waste container"
    - "Furniture"
    - "Bench"
    - "Window"
    - "Closet"
    - "Lamp"
    - "Flowerpot"
    - "Drawer"
    - "Microwave oven"
    - "Shelf"
    - "Light bulb"
    - "Kitchen & dining room table"
    - "Bathroom accessory"
    - "Kitchen appliance"
    splits: ["train", "validation", "test"]
  coco-2017:
    classes:
      - "chair"
    splits: ["train", "validation", "test"]

