

# for roboflow-dataset-import-export.ipynb
ROBOFLOW_API_KEY: AgfWlgODe2lXi5Nh5VTu
ROBOFLOW_WORKSPACE: made-srcnb
ROBOFLOW_PROJECT: room312_and_leuthener
DATASET_VERSION: 2
DATASET_TYPE: mohsen_furniture




DATASET_LOCATIONS:
  - /home/freeze/GIT/onemanstreasure/datasets/mohsen_furniture/v1/data.yaml
  - /home/freeze/GIT/onemanstreasure/datasets/mohsen_furniture/v2/data.yaml

TRAINING_CONFIGURATIONS:
  - epochs: 10
    img_size: 640
    # time: 3 # Time in hours 
    # patience: 15 # number of epochs with no improvement before stopping
    # batch: -1 # Use the default "chunks" to split the dataset for computation, -1 is auto 60% GPU utilization
  - epochs: 20
    img_size: 640
    # time: 3 # Time in hours 
    # patience: 15 # number of epochs with no improvement before stopping
    # batch: -1 # Use the default "chunks" to split the dataset for computation, -1 is auto 60% GPU utilization
  

MODEL: 
EVALUATION_DATASET: 