agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.9110508225957746
box: 15.171762858725934
cache: false
cfg: null
classes: null
close_mosaic: 6
cls: 0.24618254678068915
cls_pw: 0.7658372511738205
compile: false
conf: null
copy_paste: 0.8321867397554173
copy_paste_mode: flip
cos_lr: false
cutmix: 0.0714820534241497
data: null
degrees: 4.201943621132996
deterministic: true
device: null
dfl: 9.88783183456018
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 2
erasing: 0.4
exist_ok: false
fliplr: 0.39408743068342333
flipud: 0.7935598854383269
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.04688650508565972
hsv_s: 0.5456002352498395
hsv_v: 0.6853675542970368
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.005081435810849656
lrf: 0.5129259184709453
mask_ratio: 4
max_det: 300
mixup: 0.3967288747785074
mode: train
model: yolo26n-seg.pt
momentum: 0.9688168577739088
mosaic: 0.9065648668917633
multi_scale: 0.0
name: airvent
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: null
perspective: 4.06580587497668e-05
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.710816084853832
seed: 0
shear: 7.0853444075481695
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.20388641399407628
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 4.612172365103825
warmup_momentum: 0.1928158031310408
weight_decay: 0.0005047160225974021
workers: 8
workspace: null
