agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.15063152164232574
box: 13.528152817248362
cache: false
cfg: null
classes: null
close_mosaic: 2
cls: 3.558281750399187
cls_pw: 0.5571137071087278
compile: false
conf: null
copy_paste: 0.9678330329788167
copy_paste_mode: flip
cos_lr: false
cutmix: 0.45252608927279947
data: null
degrees: 11.811821654385328
deterministic: true
device: null
dfl: 5.912218046960852
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 3
erasing: 0.4
exist_ok: false
fliplr: 0.977935327521773
flipud: 0.2950784916073348
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.02815591193202868
hsv_s: 0.7473046724712163
hsv_v: 0.728591754880514
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.003951392594125294
lrf: 0.18111542986616794
mask_ratio: 4
max_det: 300
mixup: 0.5589904577040741
mode: train
model: yolo26n-seg.pt
momentum: 0.7368295629627136
mosaic: 0.14007464908257317
multi_scale: 0.0
name: deskchair
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: null
perspective: 0.0007482708581766619
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.8981061359628586
seed: 0
shear: 2.6236116400493215
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.0916178240931506
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 4.884955031090092
warmup_momentum: 0.14120846170401086
weight_decay: 4.3193425216066064e-05
workers: 8
workspace: null
