agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.2976306111764071
box: 3.312221808533284
cache: false
cfg: null
classes: null
close_mosaic: 1
cls: 2.1737203158150686
cls_pw: 0.1887629428698095
compile: false
conf: null
copy_paste: 0.7642876332100557
copy_paste_mode: flip
cos_lr: false
cutmix: 0.15110684074237818
data: null
degrees: 16.20192061501413
deterministic: true
device: null
dfl: 6.9726161280039305
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 3
erasing: 0.4
exist_ok: false
fliplr: 0.6089394108010724
flipud: 0.554309372720323
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.09293150848889994
hsv_s: 0.6049606933762911
hsv_v: 0.8415468705534684
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.009330713622261677
lrf: 0.15845585119788602
mask_ratio: 4
max_det: 300
mixup: 0.39460434972462927
mode: train
model: yolo26n-seg.pt
momentum: 0.7608806742759855
mosaic: 0.9937046583432971
multi_scale: 0.0
name: filing_cabinet
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: null
perspective: 0.00038445817842380623
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.706172228553813
seed: 0
shear: 7.957821744006808
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.3587751536999604
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 3.4422970662461783
warmup_momentum: 0.6897788338483641
weight_decay: 0.0006776673308906228
workers: 8
workspace: null
