agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.6156785021237946
box: 1.7469930072469664
cache: false
cfg: null
classes: null
close_mosaic: 8
cls: 2.1454709661921547
cls_pw: 0.4734236523994819
compile: false
conf: null
copy_paste: 0.3036593112556495
copy_paste_mode: flip
cos_lr: false
cutmix: 0.2847032804317138
data: null
degrees: 12.864360304509475
deterministic: true
device: null
dfl: 10.551662992501083
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 3
erasing: 0.4
exist_ok: false
fliplr: 0.6310120992704207
flipud: 0.6629320073689283
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.08526929047831865
hsv_s: 0.4856915944844822
hsv_v: 0.7003541701096351
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.004365248747589128
lrf: 0.3173887996084075
mask_ratio: 4
max_det: 300
mixup: 0.9563217130979808
mode: train
model: yolo26n-seg.pt
momentum: 0.8425787145916216
mosaic: 0.5801055928319548
multi_scale: 0.0
name: filing_cabinet
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: null
perspective: 0.0006825022944465365
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.6145840401424599
seed: 0
shear: 3.857130579531823
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.38767071005612386
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 2.7874992427738947
warmup_momentum: 0.09150104677869637
weight_decay: 0.0005032663638352275
workers: 8
workspace: null
