agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.19201613801247386
box: 4.357899246155468
cache: false
cfg: null
classes: null
close_mosaic: 5
cls: 3.365545471257146
cls_pw: 0.9836297206491952
compile: false
conf: null
copy_paste: 0.48171967272089256
copy_paste_mode: flip
cos_lr: false
cutmix: 0.3006989461503239
data: null
degrees: 43.21615149411824
deterministic: true
device: null
dfl: 2.6039421061088404
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 3
erasing: 0.4
exist_ok: false
fliplr: 0.6366308761776586
flipud: 0.05161853354041135
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.027165772707622916
hsv_s: 0.351233066763972
hsv_v: 0.8135448382110342
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.002887923127594031
lrf: 0.5671087547058217
mask_ratio: 4
max_det: 300
mixup: 0.8556168776357862
mode: train
model: yolo26n-seg.pt
momentum: 0.7836175148817465
mosaic: 0.6817192887225133
multi_scale: 0.0
name: sink
nbs: 64
nms: false
opset: null
optimize: false
optimizer: auto
overlap_mask: true
patience: null
perspective: 0.0006161115488680338
plots: true
pose: 12.0
pretrained: true
profile: false
project: cvmgr
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.6184294043185664
seed: 0
shear: 6.19518514786731
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.40988731394405287
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 4.555690012402643
warmup_momentum: 0.563957801827468
weight_decay: 0.0005191166504998147
workers: 8
workspace: null
