_wandb:
    value:
        cli_version: 0.26.1
        e:
            wiht6fktq6p8h59629e54lfkdcesz2h1:
                args:
                    - --optimize
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "207818493952"
                        used: "109968326656"
                email: starke@b-tu.de
                executable: /home/rolf/anaconda3/envs/cvmgr/bin/python
                git:
                    commit: 6b9d95f8e500df3ea82b1c4e6b24b5085cf0d350
                    remote: https://github.com/rolfstarke/cvmgr.git
                gpu: NVIDIA RTX A4000
                gpu_count: 5
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-a953b6be-4f1c-6e17-37f2-314c5185e2df
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-9323c0ec-5d7e-2d7d-352d-772492fa96e9
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-2aae169b-ecb8-ac84-90ad-19ccffecae32
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-4f5c9e64-ae39-b646-328c-29f65686286f
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-7de1de81-6635-42a0-ab53-92f20494e79b
                host: lnx-1.bauwesen.local
                memory:
                    total: "475512524800"
                os: Linux-6.8.0-88-generic-x86_64-with-glibc2.39
                program: /home/rolf/GIT/cvmgr/main.py
                python: CPython 3.10.20
                root: /home/rolf/GIT/cvmgr
                startedAt: "2026-05-08T21:48:19.673277Z"
                writerId: wiht6fktq6p8h59629e54lfkdcesz2h1
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 30
                - 35
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 30
                - 35
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.10.20
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
bgr:
    value: 0.7758257402553213
box:
    value: 16.17264687133734
close_mosaic:
    value: 9
cls:
    value: 0.48598169906961386
cls_pw:
    value: 0.28794993609256003
copy_paste:
    value: 0.02363814932042696
cutmix:
    value: 0.5628964941459828
degrees:
    value: 38.12758149723564
dfl:
    value: 9.806495200276435
fliplr:
    value: 0.5009871476144349
flipud:
    value: 0.8752561074669137
hsv_h:
    value: 0.05575212816192439
hsv_s:
    value: 0.26767867391325895
hsv_v:
    value: 0.7491171130349342
lr0:
    value: 0.007931161431350905
lrf:
    value: 0.40625344356391274
mAP50-95_M:
    value: 0.15029
mixup:
    value: 0.7787697064547527
momentum:
    value: 0.7777755642581061
mosaic:
    value: 0.309035989267176
perspective:
    value: 0.0004809103386419732
scale:
    value: 0.057913914420310214
shear:
    value: 5.957196277942534
translate:
    value: 0.8608071462127069
warmup_epochs:
    value: 2.7616990494439406
warmup_momentum:
    value: 0.518616411498943
weight_decay:
    value: 0.0008331683711626771
